name: Deploy Backend to Lightsail

on:
  push:
    paths:
      - 'backend/**'
      - 'requirements.txt'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            cd /home/ubuntu/get-in-the-pool
            git pull origin main
            # Create venv if it doesn't exist
            python3 -m venv backend/venv || true
            source backend/venv/bin/activate
            pip install -r requirements.txt
            sudo cp backend/server-config/get-in-the-pool.service /etc/systemd/system/
            sudo systemctl daemon-reload
            sudo systemctl enable get-in-the-pool
            sudo systemctl restart get-in-the-pool